### ISSUE TITLE
Can we not do this approach?

### ISSUE THREAD

**Issue by baseplate-admin** [tokitou-san/CoreProject-V3-UI#574]
https://github.com/tokitou-san/CoreProject-V3-UI/blob/e1f8a3db81a7afb4b4e67e3e95b5c54b01235f06/src/lib/components/tippies/filter_options.svelte#L1-L42

**Comment by tokitou-san** [comment]
Meaning? change tippy approach?

**Comment by baseplate-admin** [comment]
Yea dont use tippy for everything. Tippy is pretty performance intensive

**Comment by tokitou-san** [comment]
> Tippy is pretty performance intensive

Yea? also it seems values which are passed to tippy once is not updating.

**Comment by baseplate-admin** [comment]
> Yea? also it seems values which are passed to tippy once is not updating.

I can fix this. But still in general i dont like relying too much on a tooltip library

**Comment by tokitou-san** [comment]
> I can fix this. But still in general i dont like relying too much on a tooltip library

Okay? want to use skeleton this time? or make a custom uhh?

**Comment by baseplate-admin** [comment]
> Okay? want to use skeleton this time? or make a custom uhh?

Do you think skeleton popup issue is fixed?

**Comment by tokitou-san** [comment]
> Do you think skeleton popup issue is fixed?

No? I will take a look
also that flick animation on first click seems not fixed...

**Comment by baseplate-admin** [comment]
tied to :

* https://github.com/tokitou-san/CoreProject-V3-UI/issues/574

**Comment by tokitou-san** [comment]
Duplicate of #603
